#!/bin/sh
# Gradle start up script for POSIX. Generated by Gradle.
# To regenerate: run `gradle wrapper` from a machine with Gradle installed.
# This is a placeholder; download the official wrapper script from
# https://services.gradle.org/distributions/gradle-8.7-bin.zip if needed.
exec gradle "$@"
